### ISSUE TITLE
Key Error from det.py while executing detection.ipynb

### ISSUE THREAD

**Issue by NanduRaj** [pknu-wap/UnderTheSea#3]
While running the detection.ipynb, I got key error from det.py. 
It is at line :  **_**dataset_train, dataset_val = det.create_datasets(dataset_path+"/train",  config)_****

Here is the stackTrace.:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-f021db38409f> in <module>
      1 # Load dataset
      2 ## annotations파일을 불러와서 클래스 구분되는 이름을 가져온다.
----> 3 dataset_train, dataset_val = det.create_datasets(dataset_path+"/train",  config)
      4 

~/projects/fish-classification/UnderTheSea/fish_project/det.py in create_datasets(dataset_dir, config, train_pct)
    319     """
    320 
--> 321     train_ann, val_ann = split_annotations(dataset_dir, config, train_pct=train_pct)
    322 
    323     print(annotation_stats(train_ann))

~/projects/fish-classification/UnderTheSea/fish_project/det.py in split_annotations(dataset_dir, config, train_pct, annotation_filename, randomize)
    272             uniq_class_names[object_name] += 1
    273             total_classes += 1
--> 274             rc[indexes[object_name]] += 1
    275         images_classes[a['filename']] = rc
    276 

KeyError: 'lutjanus_rivulatus'

I believe it is trying to enter multiple keys to the map in det.py. I checked the json and it is a valid json, with unique names. The train images and annotations.json file is in location -> UnderTheSea/fish_project/images/fish/train/

**Comment by JaeungHyun** [comment]
Would you show me your annotation.json file?

**Comment by NanduRaj** [comment]
[annotations.zip](https://github.com/pknu-wap/UnderTheSea/files/3409730/annotations.zip)
Thanks for the response. I have attached the json file

**Comment by JaeungHyun** [comment]
@NanduRaj 
I need time to check it.

and I think you need to improve x,y points more accurately

"acanthopagrus _latus_1.jpg39724": {
        "fileref": "",
        "size": 39724,
        "filename": "acanthopagrus _latus_1.jpg",
        "base64_img_data": "",
        "file_attributes": {},
        "regions": {
            "0": {
                "shape_attributes": {
                    "name": "polygon",
                    "all_points_x": [
                        31,
                        59,
                        83,
                        98,
                        115,
                        169,
                        155,
                        169,
                        159,
                        174,
                        188,
                        208,
                        221,
                        236,
                        253,
                        261,
                        278,
                        287,
                        306,
                        308,
                        332,
                        331,
                        356,
                        350,
                        365,
                        369,
                        386,
                        384,
                        395,
                        400,
                        433,
                        456,
                        479,
                        480,
                        472,
                        435,
                        473,
                        513,
                        546,
                        602,
                        621,
                        605,
                        580,
                        603,
                        594,
                        541,
                        495,
                        478,
                        440,
                        436,
                        462,
                        463,
                        457,
                        448,
                        432,
                        435,
                        442,
                        419,
                        387,
                        375,
                        374,
                        361,
                        322,
                        283,
                        262,
                        289,
                        296,
                        289,
                        279,
                        260,
                        244,
                        239,
                        231,
                        217,
                        212,
                        147,
                        99,
                        57,
                        33,
                        40,
                        56,
                        39,
                        26,
                        31
                    ],
                    "all_points_y": [
                        268,
                        212,
                        190,
                        167,
                        151,
                        111,
                        82,
                        96,
                        50,
                        78,
                        30,
                        68,
                        26,
                        61,
                        36,
                        63,
                        45,
                        69,
                        52,
                        77,
                        60,
                        84,
                        71,
                        84,
                        81,
                        100,
                        93,
                        110,
                        109,
                        116,
                        114,
                        123,
                        158,
                        180,
                        194,
                        195,
                        210,
                        202,
                        180,
                        155,
                        151,
                        209,
                        241,
                        309,
                        323,
                        302,
                        276,
                        271,
                        277,
                        284,
                        281,
                        306,
                        337,
                        366,
                        366,
                        381,
                        395,
                        389,
                        361,
                        346,
                        358,
                        337,
                        333,
                        332,
                        331,
                        342,
                        357,
                        390,
                        416,
                        416,
                        402,
                        393,
                        388,
                        354,
                        334,
                        323,
                        308,
                        306,
                        297,
                        287,
                        283,
                        277,
                        275,
                        268
                    ]
                },
                "region_attributes": {
                    "object_name": "Fish"
                }
            }
        }
    }

Here is part of my data annotation

**Comment by JaeungHyun** [comment]
<img width="708" alt="image" src="https://user-images.githubusercontent.com/17588101/61519494-fff21a80-aa46-11e9-9d5d-6c0f3a341ef4.png">

when I try that method, it works

**Comment by NanduRaj** [comment]
It worked using my annotations.json file?
So there is some mistake I am making in running this.

Things I have done:

1) Downloaded QUT fish dataset specified in your readme file.
2) The annotations was not in the required format. So converted to the format you have mentioned in the readme. I have attached the json here.
3) I created directory images/fish/train and put my dataset and the above mentioned json in that folder.
4) I downloaded the mask_rcnn_coco.h5 model file inside models folder. 

Now I believe the rest is to run detection.ipynb to build the model and use the model to detect using detect.ipynb

Am I correct or did I missed something

**Comment by JaeungHyun** [comment]
No. I tried using my annotation file.

I don't know why it is not working

**Comment by MiladGhorbaniG** [comment]
@NanduRaj Since your annotations.json file has more than one class, you should define different fish classes by defining configurations. Look the below image:
![image](https://user-images.githubusercontent.com/47980221/89641984-1ecc8480-d8c8-11ea-943c-a49fd5694468.png)
